"""add_search_trigger

Revision ID: 530b50947528
Revises: e049085584b1
Create Date: 2026-05-14 18:57:39.707394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '530b50947528'
down_revision: Union[str, Sequence[str], None] = 'e049085584b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materias', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.alter_column('materias', 'entidades',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('idx_materia_search_vector', 'materias', ['search_vector'], unique=False, postgresql_using='gin')
    
    # Popula dados existentes
    op.execute("""
        UPDATE materias
        SET search_vector = to_tsvector('portuguese', coalesce(titulo, '') || ' ' || coalesce(texto, ''));
    """)

    # Cria o Trigger para atualizações futuras
    op.execute("""
        CREATE TRIGGER tsvector_update 
        BEFORE INSERT OR UPDATE ON materias
        FOR EACH ROW EXECUTE FUNCTION
        tsvector_update_trigger(search_vector, 'pg_catalog.portuguese', titulo, texto);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS tsvector_update ON materias")
    op.drop_index('idx_materia_search_vector', table_name='materias', postgresql_using='gin')
    op.alter_column('materias', 'entidades',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('materias', 'search_vector')
    # ### end Alembic commands ###
